CREATE TABLE Department
(
    DepartmentID BIGINT PRIMARY KEY IDENTITY(1,1),
    DepartmentName VARCHAR(255) UNIQUE NOT NULL
)

CREATE TABLE [Role] (
    RoleID BIGINT PRIMARY KEY IDENTITY(1,1),
    RoleName VARCHAR(255) UNIQUE NOT NULL
)

CREATE TABLE [User] (
    UserID BIGINT IDENTITY(1,1) PRIMARY KEY,
    UserName VARCHAR(255) UNIQUE NOT NULL,
    FName VARCHAR(255) NOT NULL,
    LName VARCHAR(255) NOT NULL,
    DOJ DATE NOT NULL,
    LastLogin DATETIME,
    Seniority DECIMAL(4, 2) CHECK (Seniority >= 0 AND Seniority <= 9.99),
    RoleID BIGINT FOREIGN KEY REFERENCES Role(RoleID),
    DepartmentID BIGINT FOREIGN KEY REFERENCES Department(DepartmentID),
    EmpCode VARCHAR(7) UNIQUE NOT NULL CHECK (EmpCode LIKE '[A-Z][A-Z][A-Z][0-9][0-9][0-9][0-9]')
)